Neos:
  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Flowpack.Neos.FrontendLogin:NeosBackend':
                pattern: Flowpack\Neos\FrontendLogin\Security\NeosRequestPattern
          'Flowpack.Neos.FrontendLogin:Frontend':
            provider: PersistedUsernamePasswordProvider
            requestPatterns:
              'Flowpack.Neos.FrontendLogin:NeosFrontend':
                pattern: Flowpack\Neos\FrontendLogin\Security\NeosRequestPattern
                patternOptions:
                  matchFrontend: true
  Neos:
    nodeTypes:
      groups:
        bureau:
          position: before general
          collapsed: false
          label: 'Bureau'
    userInterface:
      defaultLanguage: 'de'
      translation:
        autoInclude:
          'Joekolade.Bureau':
            - 'NodeTypes/*'
            - 'Main'
    fusion:
      autoInclude:
        Joekolade.Bureau: true
Flowpack:
  Neos:
    Matomo:
      host: "stats.schaefer-webentwicklung.de"
      protocol: "http"
      token_auth: "dc9fd0bb2fd65491befbb8d3b9261230"
      idSite: 1

ObisConcept:
  CookieConsent:
    enable: true
    includeJavaScript: true
    includeCss: true
    policyPageNode: '46e663ec-6a67-4868-82bd-2642f51a5f84'
    position: 'bottom'
    theme: 'block'
    palette:
      popup:
        background: '#2f8695'
        text: '#fff'
      button:
        background: '#fff'
        text: '#2f8695'
