ObisConcept:
  CookieConsent:
    enable: true                # Wether to enable the notice.
    includeJavaScript: true     # Auto-include cookieconsent's javascript file.
    includeCss: true            # Auto-include cookieconsent's stylesheet file.
    policyPageNode: '46e663ec-6a67-4868-82bd-2642f51a5f84'          # The page identifier of your privacy statement.
    translations:               # Change the translation source for custom texts.
      package: 'ObisConcept.CookieConsent'
      source: 'Main'
    position: 'bottom'          # The position of the notice. Possible Values:
                                # "bottom", "bottom-left", "bottom-right", "top"
    theme: 'block'              # The theme of the notice. Possible Values:
                                # "block", "classic", "edgeless", "wire"
    palette:
      popup:
        background: '#2f8695'      # The background color and
        text: '#fff'            # the text color of the notice box
      button:
        background: '#fff'   # The background color and
        text: '#2f8695'            # the text color of the dismiss-button
